package io.mindspice.lyra.runtime;

import io.mindspice.lyra.compiler.api.LyraCompiler;
import io.mindspice.lyra.compiler.api.SessionCompileRequest;
import io.mindspice.lyra.compiler.api.SessionCompileResult;
import io.mindspice.lyra.compiler.session.SessionSnapshot;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/** Exact occurrence/route authority tests independent of the REPL adapter. */
class NominalMemberDelegateAuthorityTest {
    private static final LyraSignature SIGNATURE = LyraSignature.parse("Fn<I32;I32>");
    private static final LyraSignature OTHER_SIGNATURE = LyraSignature.parse("Fn<U32;U32>");
    private static final ModuleId MODULE = ModuleId.path("delegate-authority.lyra");
    private static final NominalType TYPE = new NominalType(new NominalTypeId(
            MODULE, "d".repeat(64), "Holder", 0));
    private static final NominalSchema SCHEMA = new NominalSchema(TYPE, NominalSchema.Kind.CLASS, List.of(
            new NominalSchema.Member("public", FunctionType.of(List.of(PrimitiveType.I32),
                    PrimitiveType.I32), true, true, false),
            new NominalSchema.Member("hidden", FunctionType.of(List.of(PrimitiveType.I32),
                    PrimitiveType.I32), false, true, false),
            new NominalSchema.Member("fixed", FunctionType.of(List.of(PrimitiveType.I32),
                    PrimitiveType.I32), true, false, false)), List.of());

    /** Typed representation fixture mirroring the generated getter/route boundary. */
    private static final class Holder extends LyraNominalObject {
        private final Object[] values = new Object[3];

        Holder(LyraNominalConstruction construction) {
            super(construction, TYPE.canonicalSpelling());
        }

        Object generatedGet(LyraClosureAuthority caller, int field) {
            checkGeneratedRead(caller, field);
            return values[field];
        }

        Object route(LyraClosureAuthority caller, int field, Object selected,
                     LyraSignature signature) {
            // Generated bytecode obtains selected from this exact field load.
            if (field >= 0 && field < values.length && values[field] != selected) {
                throw new LyraLinkException("selected value differs from the compiler-certified field route");
            }
            return issueCallableMemberRoute(caller, field, selected, signature);
        }

        Object writeRoute(LyraClosureAuthority caller, int field, Object replacement,
                          LyraSignature signature) {
            Object route = issueCallableMemberWriteRoute(caller, field, replacement, signature);
            values[field] = replacement;
            return route;
        }

        void store(int field, Object value) {
            values[field] = value;
        }

        boolean requiresDelegation(LyraClosureAuthority caller) {
            return generatedReadRequiresDelegation(caller);
        }

        void initialize(LyraNominalConstruction ticket, int field, Object value) {
            ticket.initializeField(this, field);
            values[field] = value;
        }
    }

    private static final class Delegate extends LyraNominalMemberDelegate {
        Delegate(Object route) {
            super(route);
        }
    }

    private record Producer(ModuleLifecycle lifecycle, LyraClosure closure,
                            Holder holder) { }

    private record Caller(LyraClosureAuthority authority, ModuleHandle module,
                          LyraClosure closure) { }

    private static SessionCompileResult.Success compile(String label, String header) {
        var result = LyraCompiler.compileSession(new SessionCompileRequest(label,
                header + "let @pub identity :Fn<I32;I32> = (=> |n| n)", SessionSnapshot.empty()));
        return assertInstanceOf(SessionCompileResult.Success.class, result, result.diagnostics().toString());
    }

    private static Caller caller(LoadedArtifact loaded) {
        var module = loaded.instantiate();
        LyraClosure closure = (LyraClosure) module.export("identity", SIGNATURE).functionValue();
        return new Caller(closure.authority(), module, closure);
    }

    /** Constructs the retained object under an importing, non-source-local authority. */
    private static Producer importingProducer(SessionStorageDomain domain, boolean open) {
        var compiled = compile("delegate-imported.lyra", "import std->io\n");
        var linkage = domain.link(compiled.artifact(), 0, List.of(), List.of());
        linkage.validate(compiled.artifact().metadata());
        var key = new LyraArtifactKey(OwnerThread.capture(), RuntimeIoEnvironment.defaults(),
                linkage, false, linkage.rootLifetime(),
                new NominalTypeEnvironment(List.of(SCHEMA)));
        var lifecycle = ModuleLifecycle.forArtifact(MODULE, key);
        var ticket = LyraNominalConstruction.begin(lifecycle.closureAuthority(),
                TYPE.canonicalSpelling(), Holder.class);
        var holder = new Holder(ticket);
        var closure = new LyraClosure(lifecycle.closureAuthority(), SIGNATURE) { };
        holder.initialize(ticket, 0, closure);
        holder.initialize(ticket, 1, closure);
        holder.initialize(ticket, 2, closure);
        ticket.complete(holder);
        if (open) lifecycle.open();
        return new Producer(lifecycle, closure, holder);
    }

    private static Caller caller(SessionStorageDomain domain, String label) {
        var compiled = compile(label, "");
        return caller(LyraRuntime.loadSubmission(compiled.artifact(), LoadOptions.defaults(),
                domain.link(compiled.artifact(), 0, List.of(), List.of())));
    }

    @Test
    void delegatedRouteAuthenticatesExactObjectFieldValueAndNeverBlessesRawClosure() {
        try (var domain = new SessionStorageDomain();
             var unrelated = new SessionStorageDomain()) {
            var producer = importingProducer(domain, true);
            var consumer = caller(domain, "delegate-consumer.lyra");
            var foreign = caller(unrelated, "delegate-foreign.lyra");

            assertSame(producer.closure(), producer.holder().generatedGet(
                    consumer.authority(), 0));
            assertTrue(producer.holder().requiresDelegation(consumer.authority()));
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(producer.closure(),
                            consumer.authority(), SIGNATURE));

            assertThrows(LyraLinkException.class, () -> new Delegate(new Object()),
                    "caller-minted evidence must not construct a delegate");
            assertThrows(LyraLinkException.class, () -> producer.holder().route(
                    consumer.authority(), 99, producer.closure(), SIGNATURE));
            assertThrows(LyraLinkException.class, () -> producer.holder().route(
                    consumer.authority(), 0, producer.closure(), OTHER_SIGNATURE));
            LyraClosure wrongValue = new LyraClosure(
                    producer.lifecycle().closureAuthority(), OTHER_SIGNATURE) { };
            assertThrows(LyraLinkException.class, () -> producer.holder().route(
                    consumer.authority(), 0, wrongValue, SIGNATURE));
            assertThrows(LyraLinkException.class, () -> producer.holder().route(
                    consumer.authority(), 1, producer.closure(), SIGNATURE),
                    "private routes require the declaring producer's lexical authority");
            assertThrows(LyraLinkException.class, () -> producer.holder().writeRoute(
                    consumer.authority(), 1, consumer.closure(), SIGNATURE),
                    "private fields reject foreign lexical writes");
            assertThrows(LyraLinkException.class, () -> producer.holder().writeRoute(
                    consumer.authority(), 2, consumer.closure(), SIGNATURE),
                    "immutable fields reject route-authorized writes");
            assertThrows(LyraLinkException.class, () -> producer.holder().writeRoute(
                    consumer.authority(), 0, consumer.closure(), OTHER_SIGNATURE));
            assertThrows(LyraLinkException.class, () -> producer.holder().writeRoute(
                    consumer.authority(), 0, foreign.closure(), SIGNATURE),
                    "a writable field route does not authorize a foreign replacement");

            Object evidence = producer.holder().route(
                    consumer.authority(), 0, producer.closure(), SIGNATURE);
            var delegate = new Delegate(evidence);
            assertThrows(LyraLinkException.class, () -> new Delegate(evidence),
                    "one selected occurrence cannot mint multiple delegates");
            assertSame(producer.closure(), LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            consumer.authority(), SIGNATURE));
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(producer.closure(),
                            consumer.authority(), SIGNATURE));
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            consumer.authority(), OTHER_SIGNATURE));
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            foreign.authority(), SIGNATURE));

            domain.reset();
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            consumer.authority(), SIGNATURE));
        }
    }

    @Test
    void structuralLoaderRequiresTheDelegateExactNominalAndFunctionRouteTypes() {
        var compiled = compile("delegate-loader.lyra", """
                class Route { @pub apply :Fn<I32;I32> = (=> |n| n) }
                """);
        Map<String, byte[]> classes = compiled.artifact().classes();
        String delegateName = classes.keySet().stream()
                .filter(name -> name.contains(".$lyra$delegate$")).findFirst().orElseThrow();
        var loader = new SessionTypeLoader();
        assertDoesNotThrow(() -> loader.stage(classes));
        assertThrows(LyraLinkException.class,
                () -> new SessionTypeLoader().stage(
                        Map.of(delegateName, classes.get(delegateName))),
                "delegate admission must fail when its exact nominal/interface route types are absent");
    }

    @Test
    void sourceLocalProducersKeepExactStoredValuesWithoutDelegation() {
        try (var domain = new SessionStorageDomain()) {
            var compiled = compile("delegate-local.lyra", "");
            var linkage = domain.link(compiled.artifact(), 0, List.of(), List.of());
            var key = new LyraArtifactKey(OwnerThread.capture(), RuntimeIoEnvironment.defaults(),
                    linkage, false, null, new NominalTypeEnvironment(List.of(SCHEMA)));
            var lifecycle = ModuleLifecycle.forArtifact(MODULE, key);
            var ticket = LyraNominalConstruction.begin(lifecycle.closureAuthority(),
                    TYPE.canonicalSpelling(), Holder.class);
            var holder = new Holder(ticket);
            var closure = new LyraClosure(lifecycle.closureAuthority(), SIGNATURE) { };
            holder.initialize(ticket, 0, closure);
            holder.initialize(ticket, 1, closure);
            holder.initialize(ticket, 2, closure);
            ticket.complete(holder);
            lifecycle.open();

            var consumer = caller(domain, "delegate-local-consumer.lyra");
            assertSame(closure, holder.generatedGet(consumer.authority(), 0));
            assertFalse(holder.requiresDelegation(consumer.authority()));
        }
    }

    @Test
    void deepAndAlternatingRoutesStayFlatAndRetainEveryLifecycleDependency() {
        try (var domain = new SessionStorageDomain()) {
            var first = importingProducer(domain, true);
            var second = importingProducer(domain, true);
            var consumer = caller(domain, "delegate-flat-consumer.lyra");

            LyraNominalMemberDelegate selected = new Delegate(first.holder().route(
                    consumer.authority(), 0, first.closure(), SIGNATURE));
            for (int index = 0; index < 10_000; index++) {
                Holder holder = (index & 1) == 0 ? second.holder() : first.holder();
                selected = new Delegate(holder.writeRoute(
                        consumer.authority(), 0, selected, SIGNATURE));
                holder.store(0, selected);
                assertTrue(selected.routeDependencyCount() <= 2,
                        "repeated routes must deduplicate by exact source/field/signature identity");
            }
            assertEquals(2, selected.routeDependencyCount());
            assertSame(first.closure(), LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(
                            selected, consumer.authority(), SIGNATURE));
            assertTrue(LyraClosureSupport.sameIdentity(selected, first.closure()));

            // The selected raw closure belongs to first; retiring second proves
            // the non-target alternating dependency was retained and checked.
            second.lifecycle().close();
            LyraNominalMemberDelegate retained = selected;
            assertThrows(LyraClosedException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(
                            retained, consumer.authority(), SIGNATURE),
                    "retiring a non-target alternating source must retire the flat route");
            first.lifecycle().close();
        }
    }

    @Test
    void writableRouteUsesActualCallerAndRetainsReplacementProducerLifecycle() {
        try (var domain = new SessionStorageDomain()) {
            var producer = importingProducer(domain, true);
            var replacement = caller(domain, "delegate-replacement.lyra");
            var observer = caller(domain, "delegate-replacement-observer.lyra");

            var delegate = new Delegate(producer.holder().writeRoute(
                    replacement.authority(), 0, replacement.closure(), SIGNATURE));
            producer.holder().store(0, delegate);
            assertSame(replacement.closure(), LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(
                            delegate, observer.authority(), SIGNATURE));
            assertTrue(LyraClosureSupport.sameIdentity(delegate, replacement.closure()));

            replacement.module().close();
            assertThrows(LyraClosedException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(
                            delegate, observer.authority(), SIGNATURE));
            producer.lifecycle().close();
        }
    }

    @Test
    void initializingFailedAndClosedProducersCannotIssueOrUseRouteEvidence() {
        try (var initializingDomain = new SessionStorageDomain()) {
            var initializing = importingProducer(initializingDomain, false);
            var caller = caller(initializingDomain, "delegate-initializing-caller.lyra");
            assertThrows(LyraLifecycleException.class, () -> initializing.holder().route(
                    caller.authority(), 0, initializing.closure(), SIGNATURE));
            initializing.lifecycle().fail(new IllegalStateException("failed producer"));
            assertThrows(LyraInitializationException.class, () -> initializing.holder().route(
                    caller.authority(), 0, initializing.closure(), SIGNATURE));
        }

        try (var closedDomain = new SessionStorageDomain()) {
            var producer = importingProducer(closedDomain, true);
            var caller = caller(closedDomain, "delegate-closed-caller.lyra");
            var delegate = new Delegate(producer.holder().route(
                    caller.authority(), 0, producer.closure(), SIGNATURE));
            producer.lifecycle().close();
            assertThrows(LyraClosedException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            caller.authority(), SIGNATURE));
        }
    }

    @Test
    void rootRoutesStayScopedToOneRootAndRetireWhenThatRootCloses() {
        var root = new SessionStorageDomain.RootLifetime();
        var foreignRoot = new SessionStorageDomain.RootLifetime();
        try {
            var firstDomain = new SessionStorageDomain(root);
            var producer = importingProducer(firstDomain, true);
            var firstCaller = caller(firstDomain, "delegate-root-first.lyra");
            var delegate = new Delegate(producer.holder().route(
                    firstCaller.authority(), 0, producer.closure(), SIGNATURE));
            firstDomain.close();

            var laterDomain = new SessionStorageDomain(root);
            var laterCaller = caller(laterDomain, "delegate-root-later.lyra");
            assertSame(producer.closure(), LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            laterCaller.authority(), SIGNATURE));

            var foreignDomain = new SessionStorageDomain(foreignRoot);
            var foreignCaller = caller(foreignDomain, "delegate-other-root.lyra");
            assertThrows(LyraLinkException.class, () -> LyraClosureSupport
                    .requireAuthenticatedForGeneratedInvocation(delegate,
                            foreignCaller.authority(), SIGNATURE));
            foreignDomain.close();

            root.close();
            assertThrows(LyraClosedException.class, () -> delegate.checkUsable(SIGNATURE));
            producer.lifecycle().close();
        } finally {
            if (!root.isClosed()) root.close();
            foreignRoot.close();
        }
    }
}
