package io.mindspice.lyra.editor;

import com.sun.jdi.*;
import com.sun.jdi.event.*;
import com.sun.jdi.request.*;

import java.nio.file.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;

/** JDI controls real generated bytecode. No source interpreter or target-side toString calls. */
public final class Debugger implements AutoCloseable {
    public static final String GENERATED = "lyra.editor.generated.";
    public record Breakpoint(Path file, int line) {
        public Breakpoint { file = file.toAbsolutePath().normalize(); if (line < 1) throw new IllegalArgumentException("line"); }
    }
    public record Frame(Path file, int line, String function, Map<String, String> variables) {
        public Frame { variables = Collections.unmodifiableMap(new LinkedHashMap<>(variables)); }
        public String label() { return function + "  ·  " + file.getFileName() + ":" + line; }
    }
    public record Pause(List<Frame> frames, String reason) {
        public Pause { frames = List.copyOf(frames); }
    }
    private final VirtualMachine vm;
    private final List<Path> roots;
    private final Consumer<Pause> paused;
    private final Consumer<String> status;
    private final Map<String, Path> sources = new ConcurrentHashMap<>();
    private Set<Breakpoint> breakpoints = Set.of();
    private EventSet heldEvents;
    private ThreadReference heldThread;
    private Breakpoint entry;
    private int entryEnd;
    private volatile boolean closed;

    public Debugger(VirtualMachine vm, List<Path> roots, Consumer<Pause> paused, Consumer<String> status) {
        this.vm = vm; this.roots = List.copyOf(roots); this.paused = paused; this.status = status;
        ClassPrepareRequest prepare = vm.eventRequestManager().createClassPrepareRequest();
        prepare.addClassFilter(GENERATED + "*");
        prepare.setSuspendPolicy(EventRequest.SUSPEND_EVENT_THREAD);
        prepare.enable();
        Thread.ofPlatform().daemon().name("lyra-editor-debug-events").start(this::events);
    }

    public synchronized void registerSubmission(UUID id, Path path) {
        sources.put("repl/submission-" + id + ".lyra", path.toAbsolutePath().normalize());
        refresh();
    }
    public synchronized void setBreakpoints(Set<Breakpoint> values) {
        breakpoints = Set.copyOf(values); refresh();
    }
    public synchronized void stopAtEntry(Path path, int line, int endLine) {
        entry = new Breakpoint(path, line); entryEnd = endLine; refresh();
    }
    public synchronized void stopAtNextFunction() {
        MethodEntryRequest request = vm.eventRequestManager().createMethodEntryRequest();
        request.addClassFilter(GENERATED + "*"); request.setSuspendPolicy(EventRequest.SUSPEND_EVENT_THREAD); request.enable();
    }
    public synchronized boolean isPaused() { return heldEvents != null; }

    public synchronized void resume() {
        if (heldEvents == null) return;
        EventSet events = heldEvents;
        heldEvents = null; heldThread = null;
        status.accept("Running");
        events.resume();
    }
    public synchronized void step(int depth) {
        if (heldThread == null) return;
        var requests = vm.eventRequestManager();
        requests.deleteEventRequests(new ArrayList<>(requests.stepRequests()));
        StepRequest step = requests.createStepRequest(heldThread, StepRequest.STEP_LINE, depth);
        step.addClassFilter(GENERATED + "*");
        step.addCountFilter(1);
        step.setSuspendPolicy(EventRequest.SUSPEND_EVENT_THREAD);
        step.enable();
        resume();
    }

    private synchronized void refresh() {
        if (closed) return;
        try {
            var manager = vm.eventRequestManager();
            manager.deleteEventRequests(new ArrayList<>(manager.breakpointRequests()));
            vm.allClasses().stream().filter(type -> type.name().startsWith(GENERATED)).forEach(this::install);
        } catch (VMDisconnectedException ignored) { }
    }

    private synchronized void install(ReferenceType type) {
        try {
            Path path = source(type.sourceName());
            if (path == null) return;
            List<Location> lines = type.allLineLocations();
            Set<Integer> desired = new HashSet<>();
            breakpoints.stream().filter(point -> point.file().equals(path)).forEach(point -> desired.add(point.line()));
            if (entry != null && entry.file().equals(path)) {
                lines.stream().filter(location -> location.method().name().equals("invoke"))
                        .mapToInt(Location::lineNumber).filter(line -> line >= entry.line() && line <= entryEnd)
                        .min().ifPresent(desired::add);
            }
            for (Location location : lines) {
                if (!desired.contains(location.lineNumber())) continue;
                // One location per method/line prevents immediately stopping twice on the same statement.
                boolean exists = vm.eventRequestManager().breakpointRequests().stream()
                        .anyMatch(request -> request.location().method().equals(location.method())
                                && request.location().lineNumber() == location.lineNumber());
                if (!exists) {
                    BreakpointRequest request = vm.eventRequestManager().createBreakpointRequest(location);
                    request.setSuspendPolicy(EventRequest.SUSPEND_EVENT_THREAD);
                    request.enable();
                }
            }
        } catch (AbsentInformationException | ClassNotPreparedException ignored) { }
    }

    private Path source(String name) {
        Path registered = sources.get(name);
        if (registered != null) return registered;
        try {
            if (name.startsWith("file:")) return Path.of(java.net.URI.create(name)).toAbsolutePath().normalize();
            for (Path root : roots) {
                Path candidate = root.resolve(name).normalize();
                if (Files.isRegularFile(candidate)) return candidate.toRealPath();
            }
        } catch (Exception ignored) { }
        return null;
    }

    private void events() {
        try {
            while (!closed) {
                EventSet set = vm.eventQueue().remove(500);
                if (set == null) continue;
                boolean hold = false;
                for (Event event : set) {
                    if (event instanceof ClassPrepareEvent prepare) install(prepare.referenceType());
                    else if (event instanceof MethodEntryEvent method && method.method().name().equals("invoke")) {
                        hold = suspend(set, method.thread(), "Function entry");
                        if (hold) vm.eventRequestManager().deleteEventRequest(method.request());
                    }
                    else if (event instanceof BreakpointEvent breakpoint) {
                        hold = suspend(set, breakpoint.thread(), "Breakpoint");
                    } else if (event instanceof StepEvent step) {
                        vm.eventRequestManager().deleteEventRequest(step.request());
                        hold = suspend(set, step.thread(), "Step");
                    } else if (event instanceof VMDeathEvent || event instanceof VMDisconnectEvent) {
                        closed = true;
                    }
                }
                if (!hold && !closed) set.resume();
            }
        } catch (VMDisconnectedException ignored) {
        } catch (InterruptedException interrupted) { Thread.currentThread().interrupt();
        } catch (RuntimeException failure) { status.accept("Debugger failed: " + failure.getMessage());
        } finally {
            synchronized (this) { heldEvents = null; heldThread = null; }
            status.accept("Debugger disconnected");
        }
    }

    private synchronized boolean suspend(EventSet set, ThreadReference thread, String reason) {
        List<Frame> frames = new ArrayList<>();
        try {
            for (StackFrame frame : thread.frames(0, Math.min(thread.frameCount(), 64))) {
                Location location = frame.location();
                if (!location.declaringType().name().startsWith(GENERATED)) continue;
                Path path = source(location.sourceName());
                if (path == null || location.lineNumber() < 1) continue;
                Map<String, String> variables = new LinkedHashMap<>();
                try {
                    for (LocalVariable local : frame.visibleVariables().stream().limit(64).toList())
                        variables.put(local.name(), render(frame.getValue(local), 0));
                } catch (AbsentInformationException unavailable) {
                    List<Value> args = frame.getArgumentValues();
                    for (int i = 0; i < Math.min(args.size(), 32); i++) variables.put("argument " + (i + 1), render(args.get(i), 0));
                }
                if (frame.thisObject() != null) {
                    ObjectReference self = frame.thisObject();
                    for (Field field : self.referenceType().allFields().stream().filter(f -> !f.isStatic()).limit(32).toList())
                        variables.put("this." + field.name(), render(self.getValue(field), 0));
                }
                frames.add(new Frame(path, location.lineNumber(), location.method().name(), variables));
            }
        } catch (IncompatibleThreadStateException | AbsentInformationException failure) {
            status.accept("Cannot inspect paused frame: " + failure.getMessage());
        }
        if (frames.isEmpty()) return false;
        heldEvents = set; heldThread = thread;
        if (entry != null) { entry = null; refresh(); }
        paused.accept(new Pause(frames, reason));
        return true;
    }

    private static String render(Value value, int depth) {
        if (value == null) return "#NIL";
        if (value instanceof StringReference string) {
            String text = string.value();
            return "\"" + text.substring(0, Math.min(text.length(), 512)).replace("\n", "\\n") + (text.length() > 512 ? "…" : "") + "\"";
        }
        if (value instanceof ArrayReference array && depth < 2) {
            return "[" + String.join(", ", array.getValues(0, Math.min(array.length(), 16)).stream()
                    .map(item -> render(item, depth + 1)).toList()) + (array.length() > 16 ? ", …" : "") + "]";
        }
        if (value instanceof PrimitiveValue) return value.toString();
        if (value instanceof ObjectReference object) return object.referenceType().name() + " #" + object.uniqueID();
        return value.type().name();
    }
    @Override public synchronized void close() {
        closed = true;
        try { vm.dispose(); } catch (VMDisconnectedException ignored) { }
    }
}
